### ISSUE TITLE
ArgumentOutOfRangeException when calling "Render()" method

### ISSUE THREAD

**Issue by Israel4Ever** [jamietre/CsQuery#205]
Hi, 
I'm getting this Exception while calling the "Render()" method:
<pre>
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
</pre>

Stack trace:
<pre>
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at CsQuery.HtmlParser.HtmlData.TokenName(UInt16 tokenId)
   at CsQuery.Implementation.DomElement.get_ClassName()
   at CsQuery.Implementation.DomElement.<AttributesCollection>d__38.MoveNext()
   at CsQuery.Output.FormatDefault.RenderElementInternal(IDomObject element, TextWriter writer, Boolean includeChildren)
   at CsQuery.Output.FormatDefault.RenderStack(TextWriter writer)
   at CsQuery.Output.FormatDefault.RenderChildren(IDomObject element, TextWriter writer)
   at CsQuery.Output.FormatDefault.Render(IDomObject node)
   at CsQuery.Implementation.DomObject.Render(IOutputFormatter formatter)
   at CsQuery.Implementation.DomObject.Render()
   at CsQuery.CQ.Render()
   at **** in ***:line 61
</pre>

This is my code lines:
<pre>
dom["style, script, and some more..."].Remove();
dom.Render(); // <---- BOOM
</pre>

It's seems impossible to repro this issue. Tried few times with same URL. 
Even when it's happen, I'm change the "next code line" (next instruction pointer) to the "Render()" code line agian - and now it's working. 

My code is running with Multi-Threading. I'm pretty sure that this making problems...

How I can fix this?

Thank you.

**Comment by cn-ml** [comment]
I got that error as well. Here is my stack trace if it helps.

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at CsQuery.HtmlParser.HtmlData.TokenName(UInt16 tokenId)
   at CsQuery.Implementation.DomElement.get_ClassName()
   at CsQuery.Implementation.DomElement.<AttributesCollection>d__38.MoveNext()
   at CsQuery.Output.FormatDefault.RenderElementInternal(IDomObject element, TextWriter writer, Boolean includeChildren)
   at CsQuery.Output.FormatDefault.RenderStack(TextWriter writer)
   at CsQuery.Output.FormatDefault.Render(IDomObject node)
   at "myInternalCall CQ.Render()"
```
